# Generated by Django 5.0.3 on 2024-03-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbugsmile', '0002_opchapters_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OPchapters',
        ),
    ]
